### ISSUE TITLE
is VL53L1X compatible with VL53L3CX?

### ISSUE THREAD

**Issue by ahmadfathan** [EmotionFly/ESP32_VL53L3CX#1]
I am currently searching for a way to connect VL53L3CX to ESP32 with ESP IDF. But I cannot find any example yet about it. I have got information that VL53L3CX has 4 measurement results which is different with VL53L1CX (only 1 measurements). Now I found your repository that utilizes VL53L1X API to get measurement results. Did you able to access 4 measurements as VL53L3CX feature is? Please kindly share with me about what you did with VL53L3CX with this library. Thank you.

Regards,
A. Fathan

**Comment by EmotionFly** [comment]
Hi, the VL53L1X API repository on my github is used for validation and comparison, I actually use this routine(https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.cpp).


After understanding your problem, I checked the ST official information document for the VL53L3CX chip and I found:
(https://www.st.com/zh/imaging-and-photonics-solutions/vl53l3cx.html#)





As you said, the VL53L3CX has 4 measurements that can be output simultaneously.


After a detailed look at the VL53L1X API repository and my routines, I have some guesses.


1. In my routine, I read the RESULT__FINAL_CROSSTALK_CORRECTED_RANGE_MM_SD0 register via the IIC to get the measurement.


&nbsp; &nbsp; if (!(read_register(RESULT__RANGE_STATUS, range_status) &amp;&amp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; read_register16(RESULT__FINAL_CROSSTALK_CORRECTED_RANGE_MM_SD0, reading_mm))) {
&nbsp; &nbsp; &nbsp; &nbsp; return false;
&nbsp; &nbsp; }



Registers similar to the RESULT__FINAL_CROSSTALK_CORRECTED_RANGE_MM_SD0 register and related to 4 are:
RESULT__SPARE_0_SD1
RESULT__SPARE_1_SD1
RESULT__SPARE_2_SD1
RESULT__SPARE_3_SD1


So I guess the 4 outputs of the VL53L3CX are saved by these 4 registers.


My first suggestion to you is to read the values of these 4 registers directly through the IIC and do some processing to see if they are consistent with the individual values.




2.&nbsp;If you want to use the&nbsp; VL53L1X API repository on my github.


I've combed through the code a bit and I hope that helps.


(1)&nbsp;In the main.c file, the function VL53L1_GetRangingMeasurementData(&amp;dev, &amp;rangingData) is to get the measurement value, which is stored in the rangingData variable.


(2) In the vl53l1_api.c file, the function VL53L1_get_device_results(Dev, VL53L1_DEVICERESULTSLEVEL_FULL, presults) is to get the measured values, which are stored in the presults variable.


(3) In the vl53l1_api_core.c file, the function VL53L1_get_measurement_results(Dev, device_results_level) is to get the measurement values.


(4) In the vl53l1_api_core.c file, the function VL53L1_i2c_decode_system_results(VL53L1_SYSTEM_RESULTS_I2C_SIZE_BYTES, &amp;buffer[i2c_results&amp;buffer[i2c_buffer_offset_bytes],
				psystem_results) is to get the measurement value, which is stored in the psystem_results variable.


(5)&nbsp;In the VL53L1_i2c_decode_system_results() function of the vl53l1_register_funcs.c file, we can see that:


Get the value of&nbsp; result__final_crosstalk_corrected_range_mm_sd0.


Also get the value of:
result__spare_0_sd1
result__spare_1_sd1
result__spare_2_sd1
result__spare_3_sd1


The function calls and variable assignments are a bit confusing here, see the flowchart below:





My second suggestion for you is to get the 4 outputs of result__spare_0_sd1 via the VL53L1X API repository.


I have compared the library functions of VL53L1X and VL53L3CX on the official website, and the difference is not much, so we can use the VL53L1X library function to drive the VL53L3CX chip.（https://www.st.com/zh/embedded-software/stsw-img021.html）


Whether you succeed or fail, let me know, come on！


Regards,
EmotionFly




EmotionFly
***@***.***

AHUT/CJLU
算法工程师


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EmotionFly/ESP32_VL53L3CX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 中午12:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[EmotionFly/ESP32_VL53L3CX] is VL53L1X compatible with VL53L3CX? (Issue #1)





 
I am currently searching for a way to connect VL53L3CX to ESP32 with ESP IDF. But I cannot find any example yet about it. I have got information that VL53L3CX has 4 measurement results which is different with VL53L1CX (only 1 measurements). Now I found your repository that utilizes VL53L1X API to get measurement results. Did you able to access 4 measurements as VL53L3CX feature is? Please kindly share with me about what you did with VL53L3CX with this library. Thank you.
 
Regards,
 A. Fathan

**Comment by ahmadfathan** [comment]
Thank you for your quick response time. Also thank you for investigating. Currently, I am comparing this library with another library from [STM32Duino](https://github.com/stm32duino/VL53L3CX). The library uses arduino core, so I have to change the some function to ESP IDF framework.
