### ISSUE TITLE
Can I contribute to the repo?

### ISSUE THREAD

**Issue by ahmadfathan** [EmotionFly/ESP32_VL53L3CX#2]
I have some pull request for some fix. I have created a new branch. But I cannot publish the branch so I cannot make a pull request. Can you adjust some settings to allow me to make a pull request. 

Thank you.

Regards,
Fathan

**Comment by EmotionFly** [comment]
No problem, I've invited you to join the repository.

**Comment by ahmadfathan** [comment]
Thank you
